### ISSUE TITLE
warning ends up being skipped tests

### ISSUE THREAD

**Issue by claf** [wasilak/yamllint-junit#7]
I've started to use ansible-lint-junit and now also want to use yamllint-junit but I'm facing an issue that looks like a desired purpose but seems weird to me : warnings in my yamllint output are becoming "skipped" tests in junit. This ends up in my Jenkins server not showing any of these skipped messages so I can't see the original warnings.
Am I missing something? Do I need to setup a yamllint configuration file with every single rule being treated as errors instead of warnings?

Anyway thanks for those two projects ;)

**Comment by wasilak** [comment]
Hey @claf, would it be possible for you to provide an example of yaml which has warnings in yamllint output? I'd like to test it out :)

**Comment by claf** [comment]
Sure, here you go : 

```
---
workflow:
  stop_if_error: true
  disabled: no # comment with only one space
```

together with this yamllint.rc file as config file for yamllint : 

```
---
extends: default

yaml-files:
  - '*.yaml'
  - '*.yml'

# ignore:

rules:
  braces:
    forbid: false
    min-spaces-inside: 0
    max-spaces-inside: 1
    min-spaces-inside-empty: 0
    max-spaces-inside-empty: 0
  brackets:
    forbid: false
    min-spaces-inside: 0
    max-spaces-inside: 1
    min-spaces-inside-empty: 0
    max-spaces-inside-empty: 0
  colons:
    max-spaces-before: 0
    max-spaces-after: 1
    level: warning
  commas:
    max-spaces-before: 0
    min-spaces-after: 1
    max-spaces-after: 1
  comments:
    require-starting-space: true
    ignore-shebangs: true
    min-spaces-from-content: 2
    level: warning
  comments-indentation:
    level: warning
  document-end:
    present: false
  document-start:
    present: true
    level: warning
  empty-lines:
    max: 2
    max-start: 0
    max-end: 0
    level: warning
  empty-values:
    forbid-in-block-mappings: false
    forbid-in-flow-mappings: true
  hyphens:
    max-spaces-after: 1
  indentation:
    spaces: 2
    indent-sequences: true
    check-multi-line-strings: false
  key-duplicates: enable
  key-ordering: disable
  line-length: disable
  new-line-at-end-of-file:
    level: warning
  new-lines:
    type: unix
  octal-values: disable
  quoted-strings:
    quote-type: any
    required: false
    extra-required: []
    extra-allowed: []
  trailing-spaces: enable
  truthy:
    allowed-values: ['yes', 'no']
```

This file produces 2 warnings (one for the truthy value and one for the comment too close to code) which are then translated in "skipped" entries in the xml file produced by yamllint-junit.
